spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
    - org.apache.dubbo.rpc.Filter
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    '[org.mybatis.spring]': debug
    '[org.zkit.support.server]': debug
