stages:
    - build
    - package

cache:
    paths:
        - server-account/server-account-service/target/

build_account:
    stage: build
    only:
        - main
    tags:
        - dev
    script:
        - mvn clean install
        - cd server-account/server-account-service
        - mvn package

package_account:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-account/server-account-service
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_IID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_IID $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:latest
