stages:
    - deploy
    - package

deploy_account:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd server-account/server-account-api
        - mvn clean deploy -s ../../settings.xml

package_account:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - server-account/server-account-service/target/*.jar
    script:
        - cd server-account/server-account-service
        - mvn clean package
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:latest
