stages:
    - maven
    - package
    - deploy

maven-deploy:
    stage: maven
    only:
        - main
    tags:
        - dev
    script:
        - mvn clean deploy -U -s settings.xml -Dmaven.test.skip=true

package-account:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-account/server-account-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:latest

package-mail:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-mail/server-mail-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/mail:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/mail:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/mail:latest

package-openai:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-openai/server-openai-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/openai:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/openai:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/openai:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/openai:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/openai:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/openai:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/openai:latest

package-assets:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-assets/server-assets-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/assets:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/assets:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/assets:latest

deploy-account:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-account
        - docker compose down
        - docker compose up -d

deploy-mail:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-mail
        - docker compose down
        - docker compose up -d

deploy-openai:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-openai
        - docker compose down
        - docker compose up -d

deploy-assets:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-assets
        - docker compose down
        - docker compose up -d
