stages:
    - package
    # - deploy

package:
    stage: package
    only:
        variables:
            - $SERVICE == "account"
    tags:
        - dev
    script:
        - cd server-$SERVICE/server-$SERVICE-api
        - mvn clean install
        - cd ../server-$SERVICE-service
        - mvn clean package
        - docker build -t clover-server-$SERVICE:$CI_PIPELINE_IID -f ./Dockerfile .

# deploy:
#     stage: deploy
#     only:
#         variables:
#             - $SERVICE == "main"
#             - $SERVICE == "admin"
#             - $SERVICE == "i18n"
#     tags:
#         - dev
#     script:
#         - cd /opt/clover/test/web-$SERVICE
#         - docker-compose down
#         - docker-compose up -d
