stages:
    - package
    # - deploy

package:
    stage: package
    tags:
        - dev
    script:
        - mvn package

# deploy:
#     stage: deploy
#     only:
#         variables:
#             - $SERVICE == "main"
#             - $SERVICE == "admin"
#             - $SERVICE == "i18n"
#     tags:
#         - dev
#     script:
#         - cd /opt/clover/test/web-$SERVICE
#         - docker-compose down
#         - docker-compose up -d
