stages:
    - maven
    - package
    - deploy

maven-deploy:
    stage: maven
    only:
        - main
    tags:
        - dev
    script:
        - mvn clean deploy -s settings.xml

package-account:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - server-account/server-account-service/target/*.jar
    script:
        - cd server-account/server-account-service
        - mvn clean package
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:latest

package-openai:
    stage: package
    only:
        - main
    tags:
        - openai
    script:
        - cd server-openai/server-openai-service
        - mvn clean package
        - docker build -t easy-kit-dev/server/openai:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag easy-kit-dev/server/openai:$CI_PIPELINE_ID easy-kit-dev/server/openai:latest

deploy-account:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-account
        - docker-compose down
        - docker-compose up -d

deploy-openai:
    stage: deploy
    only:
        - main
    tags:
        - openai
    script:
        - cd ~/server/openai
        - docker compose down
        - docker compose up -d
