stages:
    - build
    - package

build_account:
    stage: build
    only:
        - main
    tags:
        - dev
    script:
        - mvn clean install
        - cd server-account/server-account-service
        - mvn package

package_account:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t easy-server-account:$CI_PIPELINE_IID -f ./Dockerfile .
        - docker tag easy-server-account:$CI_PIPELINE_IID easy-server-account:latest
        - docker push easy-server-account:latest
