stages:
    - package
    - deploy

package:
    stage: package
    only:
        variables:
            - $SERVICE == "account"
    tags:
        - dev
    script:
        - mvn clean install
        - cd server-$SERVICE/server-$SERVICE-service
        - mvn package
        - docker build -t easy-server-$SERVICE:$CI_PIPELINE_IID -f ./Dockerfile .
        - docker tag easy-server-$SERVICE:$CI_PIPELINE_IID easy-server-$SERVICE:latest

deploy:
    stage: deploy
    only:
        variables:
            - $SERVICE == "account"
    tags:
        - dev
    script:
        - cd /opt/easy/server-$SERVICE
        - docker-compose down
        - docker-compose up -d
