stages:
    - package
    - deploy

package-account:
    stage: package
    only:
        - /^account-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - mvn install -Dmaven.test.skip=true
        - cd server-account/server-account-api
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-account/server-account-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/account:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/account:latest

package-mail:
    stage: package
    only:
        - /^mail-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - mvn install -Dmaven.test.skip=true
        - cd server-mail/server-mail-api
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-mail/server-mail-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/mail:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/mail:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/mail:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/mail:latest

package-assets:
    stage: package
    only:
        - /^assets-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - mvn install -Dmaven.test.skip=true
        - cd server-assets/server-assets-api
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-assets/server-assets-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin $CI_REGISTRY
        - docker build -t $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID $CI_REGISTRY/easy-kit-dev/server/assets:latest
        - docker push $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/easy-kit-dev/server/assets:latest
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/assets:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/easy-kit-dev/server/assets:latest

deploy-account:
    stage: deploy
    only:
        - /^account-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-account
        - docker compose down
        - docker compose up -d

deploy-mail:
    stage: deploy
    only:
        - /^mail-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-mail
        - docker compose down
        - docker compose up -d

deploy-ai:
    stage: deploy
    only:
        - /^ai-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - mvn install -Dmaven.test.skip=true
        - cd server-ai/
        - mvn clean deploy -U -s ../settings.xml -Dmaven.test.skip=true

deploy-assets:
    stage: deploy
    only:
        - /^assets-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-assets
        - docker compose down
        - docker compose up -d
